### ISSUE TITLE
一些代码相关的问题

### ISSUE THREAD

**Issue by Mysteriousplayer** [kaipengfang/ProS#2]
您好，有两个关于代码的问题想请教一下您。
在DomainNet的相关实验中：
1）gallery domain（Real Images）不参与训练吗？
2）Seen Domain的作用是什么，为什么要把Seen Domain作为query来进行evaluate？
感谢。

**Comment by kaipengfang** [comment]
real image 参与训练，gallery也划分成了test train
seen domain 就是训练的domain，这是遵循最早提出UCDR的工作的codebase的写法，为什么要把Seen Domain作为query来进行evaluate这个问题我没太懂。

建议查看dataload等部分的代码

**Comment by Mysteriousplayer** [comment]
关于问题1）
![1716266233317](https://github.com/fangkaipeng/ProS/assets/30040131/873efe03-0e30-4a11-8860-f6cd44b13e3a)
domainnet.py中，这部分设定了gallery domain不属于query_domains_to_train吧？
![1716266404140](https://github.com/fangkaipeng/ProS/assets/30040131/3b37abac-2235-4aaf-bd48-0469aac3fb17)
log中train_domain不包含real domain.  

关于问题2）
![1716266508429](https://github.com/fangkaipeng/ProS/assets/30040131/c231a47c-8a3c-48a9-8506-6eb1acc89526)
比如config设为 Seen:painting; Unseen:clipart
Validation 是应该用clipart作为query的吧。这里还把painting作为query是什么作用呢？
感谢。

**Comment by kaipengfang** [comment]
（1）log中train_domain少输出了real，具体看代码是把real中的Training class加到训练集中的，包括log中会输出一个字典，类似：
{'clipart': 0,'painting': 1, 'quickdraw': 2, 'real': 3,'sketch': 4}，这里是包含real了的，主要看classes的数量，300类应该就是对的
（2）painting作为query是评测只有Unseen Class，Domain是Seen的情况，这是另外一个setting。

**Comment by Mysteriousplayer** [comment]
您好，还有两个问题希望您能解答一下。
（1）sketchy dataset 的extended photos无法下载。download_sketchy.sh中的这个链接无法访问。是否可以提供一个新的链接？
![1716814638457](https://github.com/fangkaipeng/ProS/assets/30040131/1b60d91c-8828-4933-b75e-fec136e0ae2b)
（2）TUBerlin上的实验结果有些出入。我把按照reproduce_runs.sh里的指令跑出的log放在附件内，您看下是不是config或者哪里错了。
[ProS_TUBerlin_v3.log](https://github.com/fangkaipeng/ProS/files/15456226/ProS_TUBerlin_v3.log)

感谢

**Comment by Gavin001201** [comment]
> 您好，还有两个问题希望您能解答一下。 （1）sketchy dataset 的extended photos无法下载。download_sketchy.sh中的这个链接无法访问。是否可以提供一个新的链接？ ![1716814638457](https://private-user-images.githubusercontent.com/30040131/334109422-1b60d91c-8828-4933-b75e-fec136e0ae2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcyMzQ3NDksIm5iZiI6MTcxNzIzNDQ0OSwicGF0aCI6Ii8zMDA0MDEzMS8zMzQxMDk0MjItMWI2MGQ5MWMtODgyOC00OTMzLWI3NWUtZmVjMTM2ZTBhZTJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAxVDA5MzQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4MGIzZDRiNGQ0NDFmMzA0MjUwYmFiZmYzOTBkYjQ4ZDYxZWZmZGU0NDE5NGUzZTJlMDFhZDQ1NTk2YjZjOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x6sPhM6TcyOFuMi94MJ2papVl9tIm3cofOV_C1fqYaI) （2）TUBerlin上的实验结果有些出入。我把按照reproduce_runs.sh里的指令跑出的log放在附件内，您看下是不是config或者哪里错了。 [ProS_TUBerlin_v3.log](https://github.com/fangkaipeng/ProS/files/15456226/ProS_TUBerlin_v3.log)
> 
> 感谢

我也遇到了相同的问题

**Comment by pSGAme** [comment]
我也遇到了相同的问题

**Comment by pSGAme** [comment]
@Mysteriousplayer  哥，可以发一份TU-Berlin的images数据集不？ 小弟万分感谢呀！！ 1197367782@qq.com

**Comment by pSGAme** [comment]
@Mysteriousplayer  我感觉是作者记录错了，这比VPT高了11个有点夸张....

**Comment by kaipengfang** [comment]
@Mysteriousplayer 你的TU-Berlin数据量好像和我的不太一样，下面是我的某个TU-berlin训练log：

# Classes - Tr:245; Va:20; Te:30
{'images': 0, 'sketches': 1}
#Tr samples:199237; #Val queries:80; #Val gallery samples:1477.

***Validation***
#Test queries:2000; #Test gallery samples:22833.
Query Emb Dim:torch.Size([2000, 512]); Gallery Emb Dim:torch.Size([22833, 512])
Epoch Time:8m16s lr:0.0000708 mAP:0.6675 prec:0.7442

**Comment by kaipengfang** [comment]
Sketchy和TU-Berlin数据我找时间上传一下

**Comment by kaipengfang** [comment]
Sketchy：https://drive.google.com/drive/folders/1IGmRIP826s_aGYq004vbJfyaMGsCmUeD?usp=sharing,

TU-berlin：https://drive.google.com/drive/folders/1qTEe5DjGdh45UFfGa6Ofy_80yJRp7uI5?usp=sharing
